// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJwueGf2H4Smji_mH33qAmbqZ8Ae5KBI4',
    appId: '1:21867529241:web:ae61c9f137f7df65441688',
    messagingSenderId: '21867529241',
    projectId: 'x9concierge-92501',
    authDomain: 'x9concierge-92501.firebaseapp.com',
    storageBucket: 'x9concierge-92501.firebasestorage.app',
    measurementId: 'G-2536L3SRHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAttwqWHLRweH40qKB9nuy-cUNTno9GvZE',
    appId: '1:21867529241:android:3006012d10aa00e1441688',
    messagingSenderId: '21867529241',
    projectId: 'x9concierge-92501',
    storageBucket: 'x9concierge-92501.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC32d1FHLGfsWpJgV9dNDcO2KYf3GAYMsg',
    appId: '1:21867529241:ios:c45e67fbacc4aa01441688',
    messagingSenderId: '21867529241',
    projectId: 'x9concierge-92501',
    storageBucket: 'x9concierge-92501.firebasestorage.app',
    iosBundleId: 'com.example.x9Concierge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC32d1FHLGfsWpJgV9dNDcO2KYf3GAYMsg',
    appId: '1:21867529241:ios:c45e67fbacc4aa01441688',
    messagingSenderId: '21867529241',
    projectId: 'x9concierge-92501',
    storageBucket: 'x9concierge-92501.firebasestorage.app',
    iosBundleId: 'com.example.x9Concierge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJwueGf2H4Smji_mH33qAmbqZ8Ae5KBI4',
    appId: '1:21867529241:web:ea45b747060c24b4441688',
    messagingSenderId: '21867529241',
    projectId: 'x9concierge-92501',
    authDomain: 'x9concierge-92501.firebaseapp.com',
    storageBucket: 'x9concierge-92501.firebasestorage.app',
    measurementId: 'G-G34PZT5L3B',
  );

}